# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Title.delete_all
Title.connection.execute("delete from sqlite_sequence where name='titles'")
Title.create(kyouka: "国語表現Ⅰ")
Title.create(kyouka: "数学Ⅱ")
Title.create(kyouka: "日本史 A")
Title.create(kyouka: "世界史")
Title.create(kyouka: "科学と人間生活")
Title.create(kyouka: "生物")
Title.create(kyouka: "現代社会")
Title.create(kyouka: "家庭総合")
Title.create(kyouka: "簿記")
Title.create(kyouka: "ビジネス情報")
Title.create(kyouka: "プログラミング")
Title.create(kyouka: "ビジネス基礎")
Title.create(kyouka: "ビジネス管理")
Title.create(kyouka: "総合実践")
Title.create(kyouka: "電子商取引")
Title.create(kyouka: "LHR")
Title.create(kyouka: "体育")
Title.create(kyouka: "保健体育")
Title.create(kyouka: "コミュニケーション英語Ⅱ")
Title.create(kyouka: "EC")
Title.create(kyouka: "ビジネス実務")
Title.create(kyouka: "課題研究")
Title.create(kyouka: "広告と販売促進")
Title.create(kyouka: "ビジネス経済応用")
Title.create(kyouka: "財務会計Ⅱ")
Title.create(kyouka: "芸術音楽")
Subject.delete_all
Subject.connection.execute("delete from sqlite_sequence where name='subjects'")
Subject.create(title: "国語表現Ⅰ")
Subject.create(title: "数学Ⅱ")
Subject.create(title: "日本史 A")
Subject.create(title: "世界史")
Subject.create(title: "科学と人間生活")
Subject.create(title: "生物")
Subject.create(title: "現代社会")
Subject.create(title: "家庭総合")
Subject.create(title: "簿記")
Subject.create(title: "ビジネス情報")
Subject.create(title: "プログラミング")
Subject.create(title: "ビジネス基礎")
Subject.create(title: "ビジネス管理")
Subject.create(title: "総合実践")
Subject.create(title: "電子商取引")
Subject.create(title: "LHR")
Subject.create(title: "体育")
Subject.create(title: "保健体育")
Subject.create(title: "コミュニケーション英語Ⅱ")
Subject.create(title: "EC")
Subject.create(title: "ビジネス実務")
Subject.create(title: "課題研究")
Subject.create(title: "広告と販売促進")
Subject.create(title: "ビジネス経済応用")
Subject.create(title: "財務会計Ⅱ")
Subject.create(title: "芸術音楽")
Subject.create(title: ""

Teacher.delete_all
Teacher.connection.execute("delete from sqlite_sequence where name='teachers'")
Teacher.create(sensei: "日向信之")
Teacher.create(sensei: "中澤雅美")
Teacher.create(sensei: "佐藤魁人")
Teacher.create(sensei: "林奈央子")
Teacher.create(sensei: "真庭佳子")
Teacher.create(sensei: "寺本英明")
Teacher.create(sensei: "森岡彰子")
Teacher.create(sensei: "安田礼子")
Teacher.create(sensei: "岩成修司")
Teacher.create(sensei: "高見保宏")
Teacher.create(sensei: "有藤克己")
Teacher.create(sensei: "石原恵美子")
Teacher.create(sensei: "原田泰拓")
Teacher.create(sensei: "福間健広")
Teacher.create(sensei: "増野浩")
Teacher.create(sensei: "三島武徳")
Teacher.create(sensei: "森山秀樹")
Teacher.create(sensei: "山崎孝之")
Teacher.create(sensei: "曽田裕司")
Teacher.create(sensei: "水上誠")
Teacher.create(sensei: "若槻義雄")
Teacher.create(sensei: "山尾祐子")
Teacher.create(sensei: "新宮研一")
Teacher.create(sensei: "小谷一郎")
Teacher.create(sensei: "伊藤真奈美")
Teacher.create(sensei: "加藤豊")
Teacher.create(sensei: "武田敏行")
Teacher.create(sensei: "原美咲")
Teacher.create(sensei: "行武望")
Teacher.create(sensei: "吾郷睦己")
Teacher.create(sensei: "足立真美")
Teacher.create(sensei: "曽田茂子")
Teacher.create(sensei: "川上佳穂")
Teacher.create(sensei: "山尾哲彦")
Teacher.create(sensei: "中島典子")
Teacher.create(sensei: "錦織朋之")
Teacher.create(sensei: "佐和泉美")
Teacher.create(sensei: "山根一天")
Teacher.create(sensei: "高橋諒太")
Teacher.create(sensei: "角折義男")
Teacher.create(sensei: "森本真晃")
Teacher.create(sensei: "福間美穂")
Teacher.create(sensei: "小西慶一")
Teacher.create(sensei: "楫康治")
Teacher.create(sensei: "槇原千恵")
Teacher.create(sensei: "吾郷里美")
Teacher.create(sensei: "川端拓")
Teacher.create(sensei: "舟津由佳")
Teacher.create(sensei: "中尾久美子")
Teacher.create(sensei: "曽田博美")
Teacher.create(sensei: "安部和美")
Teacher.create(sensei: "安部雅夫")
Teacher.create(sensei: "井上大洋")
Teacher.create(sensei: "沖野浩之")
Teacher.create(sensei: "小椋茂夫")
Teacher.create(sensei: "鴨木美紀子")
Teacher.create(sensei: "小玉大介")
Teacher.create(sensei: "後藤光昭")
Teacher.create(sensei: "佐々木聡")
Teacher.create(sensei: "佐藤真志")
Teacher.create(sensei: "田中大介")
Teacher.create(sensei: "野々村聖")




Grate.delete_all
Grate.connection.execute("delete from sqlite_sequence where name='grates'")
Grate.create(gakunen: "1")
Grate.create(gakunen: "1")
Grate.create(gakunen: "1")


Gclass.delete_all
Gclass.connection.execute("delete from sqlite_sequence where name='glasses'")
Gclass.create(kumi: "1")
Gclass.create(kumi: "2")
Gclass.create(kumi: "3")
Gclass.create(kumi: "4")
